### ISSUE TITLE
MessageFailed not found in Provider

### ISSUE THREAD

**Issue by GavinCS** [tylernathanreed/laravel-sms#1]
When trying to send an SMS, I get the following error
`Class "Reedware\LaravelSMS\MessageFailed" not found`
`Reedware\LaravelSMS\Provider::dispatchFailedEvent
vendor/reedware/laravel-sms/src/Provider.php:473
`

Easily solved by adding `use Reedware\LaravelSMS\Events\MessageFailed;` to the use statements
in vendor/reedware/laravel-sms/src/Provider.php

**Comment by tylernathanreed** [comment]
This has been fixed.
